on:
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch: # run manually
    types:
      - check-link

name: Broken Link Check
jobs:
  check:
    # Prevents action on forks
    if: github.repository == 'apollo-elements/apollo-elements'
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://apolloelements.dev
          RECURSIVE: true
          EXCLUDED_KEYWORDS: |
            camo.githubusercontent.com
            t.me
